name: POC Test
on:
  # push:
  #   branches:
  #     - frameworkstructure
  workflow_dispatch:     # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '23' # Specify your Node.js version here

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        
      - name: Prepare Allure history
        run: |
          cd ..
          mkdir -p allure-results

      - name: Run Playwright Tests
        run: |
            npx playwright test tests/specs/sfcc/regression/GuestUser_E2EOrderShipToHome.spec.js --workers=1 --config=Configurations/playwright.config.js
        env:
          TEST_APP: sfcc
          TEST_ENV: uat
          PASSWORD: Apva@2025
        continue-on-error: true

      - name: Generate Allure report
        run: npx allure generate allure-report --clean -o allure-report
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10
          

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true
          user_name: VyshnavGspann
          user_email: vyshnav.chavala@gspann.com
